import java.awt.Color;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EL
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProgressBar = new javax.swing.JProgressBar();
        points = new javax.swing.JLabel();
        pourcentage = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1070, 10));

        points.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\gifs\\c43b2d56b4ec611ac450e6782f7143b7.gif")); // NOI18N
        getContentPane().add(points, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 460, 120));

        pourcentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pourcentage.setText("0%");
        getContentPane().add(pourcentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));

        count.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(count, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 730, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        setSize(new java.awt.Dimension(1086, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Loading load = new Loading();
        load.setVisible(true);
        
        try
        {
            for(int i = 1; i<=100; i++)
            {
                Thread.sleep(100);
                load.ProgressBar.setValue(i);
                
                if(i==0)
                {
                    load.count.setText(""+"Chargement de l'application");
                }
                else if(i==5)
                {
                    load.count.setText(""+"Préparation de la base de données");
                }
                else if(i==26)
                {
                    load.count.setText(""+"Connexion à la base de données établie");
                }
                else if(i==37)
                {
                    load.count.setText(""+"Extraction de données");
                }
                else if(i==42)
                {
                    load.count.setText(""+"Recherche des mis à jour");
                }
                else if(i==50)
                {
                    load.count.setText(""+"Optimisation de l'application");
                }
                else if(i==66)
                {
                    load.count.setText(""+"Régroupement et initialisation");
                }
                else if(i==74)
                {
                    load.count.setText(""+"Ne quittez pas cette fénêtre");
                }
                else if(i==89)
                {
                    load.count.setText(""+"Veuillez patienter");
                }
                else if(i==96)
                {
                    load.count.setText(""+"Veuillez patienter");
                }
                else if(i==100)
                {
                    load.count.setText(""+"On est prêt!!");
                }
                
                /*load.points.setVisible(true);*/
                load.pourcentage.setText(""+i+" %");
            }
        }
        catch (Exception e)
        {
            System.err.println(e);
        }
        Login open = new Login();
        load.setVisible(false);
        open.setVisible(true);
        load.dispose();
        
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel count;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel points;
    private javax.swing.JLabel pourcentage;
    // End of variables declaration//GEN-END:variables
}
